### ISSUE TITLE
Right Alignment Adjustment After Window Size Change

### ISSUE THREAD

**Issue by brownts** [Artawower/blamer.el#11]
The right alignment should be recomputed after any window size change has occurred, when using the `overlay-right` configuration.  For example, suppose you have two windows with a vertical split.  Blamer.el will have computed the window size for this and aligned the blame overlay based on the size of the window.  However, when you perform a  "C-x 1" to change to a single window frame, the corresponding blame overlay is not adjusted so that it is at the right-most side of the of the window.  It seems that Blamer.el should recompute the position of the right alignment whenever the window size changes.

**Comment by Artawower** [comment]
Done. Now It looks more responsive 🙂

**Comment by brownts** [comment]
Works great!  Thank You.
