### ISSUE TITLE
Overlay Should only Display in Active Window

### ISSUE THREAD

**Issue by brownts** [Artawower/blamer.el#12]
Especially when using the right-alignment setting, there are problematic display issues with showing the overlay in all windows where the buffer resides.  Consider the example where there are two windows in a frame with a vertical split where one of the windows consumes 2/3 the frame width and the other window consumes 1/3 the frame width.  The window width sizes are different so when the window width is calculated and the right-alignment overlay is applied to both windows, one of them will be off.  One of the windows (the inactive one) will have the overlay placed incorrectly.  Either the overlay will be placed too far to the right and cause a wrap around (or truncate) in the window, or the overlay will be placed too far left well within the bounds of the window.

In order to address this issue, it is suggested that the overlay only be visible on the active window.  This should be controllable through the overlay's "window" property which will allow the overlay to only be visible on a specific window.

**Comment by Artawower** [comment]
Thanks! Good idea as usual 🤝 Implemented last commit

**Comment by brownts** [comment]
No problem, thanks for making this package. :+1:
