### ISSUE TITLE
(error "Invalid face" org-block) when point is in a org source code block

### ISSUE THREAD

**Issue by alvarogonzalezsotillo** [Artawower/blamer.el#16]
I get the following error when point is in a [orgmode source code block](https://orgmode.org/manual/Structure-of-Code-Blocks.html):
    
     Error running timer ‘blamer--render’: (error "Invalid face" org-block)

This is an example of stack trace I got with `toggle-debug-on-error`:

```
Debugger entered--Lisp error: (error "Invalid face" org-block)
  internal-get-lisp-face-attribute((org-block) :background nil)
  face-attribute((org-block) :background)
  blamer--get-background-color()
  blamer--format-commit-info("3ab0fe69" "blamer" "You" "2021-11-12" "12:31:17" 36)
  blamer--create-popup-msg((:commit-hash "3ab0fe69" :commit-author "You" :commit-date "2021-11-12" :commit-time "12:31:17" :raw-commit-author "alvaro@thinkpad" :commit-message "blamer"))
  blamer--render()
  apply(blamer--render nil)
  timer-event-handler([t 0 0 500000 nil blamer--render nil idle 0 nil])
```

It doesn't seem caused due to my `init.el`, since it can be reproduced even with `emacs -q` and the following configuration

    (package-initialize)
    (require 'blamer)
    (global-blamer-mode)

I have wrapped `blammer--get-backgroud-color` with a `ignore-errors` macro, but maybe you can find a better solution.

**Comment by Artawower** [comment]
What will happen if you `describe-face` and type org-block? Is it exist? 
Its little bit strange, cause i thought if face applied to string it has to exist..if it exists can you eval `(face-attribute 'org-block :background)`?

Maybe there's something I don't know about faces, i'll investigate it

**Comment by Artawower** [comment]
Found an error! Please check last commit 😊

**Comment by alvarogonzalezsotillo** [comment]
It works for me now.

Thanks!
