### ISSUE TITLE
blamer--git-exist-p raises error when editting using Tramp's /sudo::/

### ISSUE THREAD

**Issue by daanturo** [Artawower/blamer.el#30]
Steps:
1. `find-file` `/sudo::/etc/fstab`
2. The file may not be opened, try again
3. `M-x`

After step 1 and 3, an error is logged: `Not a Tramp file name: "nil"`
After step 3, Emacs is unable to execute anything because the above error always stands in the way.

`blamer--git-exist-p` uses `blamer--get-local-name`/`tramp-dissect-file-name` on `nil` (a non-file mini buffer in step 3).

**Comment by Artawower** [comment]
Thanks for the good explanation. Should be fixed in the last commit

**Comment by daanturo** [comment]
Thank you, it's solved.
