### ISSUE TITLE
Four issues; setting the color of the blamer foreground color, commit messages not displaying, time is off, global mode not working

### ISSUE THREAD

**Issue by servytor** [Artawower/blamer.el#31]
I have four issues:

1. The blamer foreground color should be able to be assigned to a color. I would like it if the text was black, for example.
2. The commit messages are not displaying for me, I do not know why. It does tell me if it is uncommitted though.
3. Time for me is off by 5 hours (I am on a mac if that matters)
4. (global-blamer-mode 1) does not work. I have to turn it off and on again for it to start to work.

**Comment by Artawower** [comment]
1. If you talk about right overlay you can override blamer-face, for example
```
(use-package blamer
  :ensure t
  ;; Other configs
  :custom-face
  (blamer-face ((t :foreground "black" ;; You can write the hex code
                    :background nil)))
  :config
  (global-blamer-mode 1))
  ```
If the spech is about pretty-popup check next font faces: `blamer-pretty-commit-message-face`, `blamer-pretty-meta-keywords-face` and `blamer-pretty-meta-data-face`
2. I need more info a bit. Under hood blamer use git api,  could you type `git blame -L <line-number-with-problem>,<line-number-with-problem> <your-file-name>`, is it uncommitted changes?   
3. Is the time zone in the CLI correct? (You can check this with the `date` command, or check the previous git blame command)
4. Are you sure that the blamer package was initialized? Try to delete the :defer/:after keyword from use-package, is it same result?

**Comment by servytor** [comment]
1. I fixed it, that was my mistake in understanding 
2. I have no idea
3. Yup, date works perfectly for me in the CLI. I tried eshell as well to see if it is Emacs specific.
4. This is the one that is killing me. There is no :defer/:after keyword, I have (global-blamer-mode 1) and it is weird. What happens is that when editing, I will then try to enable it, it tells me I have now disabled it, but then I M-x start it again, and it works perfectly. I have no clue what could be causing the issue.

**Comment by Artawower** [comment]
For points 2-3, show me the output of the command `git blame -L <number of line with problem>,<number of line with problem> <name of your file>`.
4. Yes, this looks very strange. Could you show me your settings? Or you could try running emacs with the -Q flag and run only blamer? Is it the same behavior?

**Comment by servytor** [comment]
Here, I will focus on the starting it issue. I was able to recreate the issue with the following init file:

`;;; init.el --- a simple package initialization routine

;;; Commentary:
(setq mac-command-modifier 'meta)
;; setup package archives
(setq package-archives
      ;; ("elpa" .         "https://tromey.com/elpa/")
      '(("melpa" .        "https://melpa.org/packages/")
        ("melpa-stable" . "https://stable.melpa.org/packages/")
        ("gnu" .          "https://elpa.gnu.org/packages/")
        ("org" .          "https://orgmode.org/elpa/")))

(require 'package)
(setq package-enable-at-startup nil)
(package-initialize)

;; bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; bootstrap `quelpa'
(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))

;; use quelpa with use-package
(quelpa
 '(quelpa-use-package
   :fetcher git
   :url "https://github.com/quelpa/quelpa-use-package.git"))
(require 'quelpa-use-package)


(unless (package-installed-p 'quelpa)
    (with-temp-buffer
      (url-insert-file-contents "https://github.com/quelpa/quelpa/raw/master/quelpa.el")
      (eval-buffer)
      (quelpa-self-upgrade)))

;; straight
;; (defvar bootstrap-version)
;; (let ((bootstrap-file
;;        (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
;;       (bootstrap-version 5))
;;   (unless (file-exists-p bootstrap-file)
;;     (with-current-buffer
;;         (url-retrieve-synchronously
;;          "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
;;          'silent 'inhibit-cookies)
;;       (goto-char (point-max))
;;       (eval-print-last-sexp)))
;;   (load bootstrap-file nil 'nomessage))

(use-package blamer
  :ensure t
  :bind (("s-i" . blamer-show-commit-info))
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  (blamer-commit-formatter "● %s")
  (blamer-smart-background-p nil)
  :custom-face
  (blamer-face ((t :height 140
                   :italic t)))
  :config
  (global-blamer-mode 1)
  ;; (add-hook 'emacs-startup-hook #'(lambda () (global-blamer-mode 1)))
  ;;  :config
  )



;; (setq dotfiles-dir (file-name-directory (or (buffer-file-name) load-file-name)))

;; (let* ((started-at (current-time))
;;        (org-dir (expand-file-name
;;                  "lisp" (expand-file-name
;;                          "org" (expand-file-name
;;                                 "src" dotfiles-dir))))
;;        (org-contrib-dir (expand-file-name
;;                          "lisp" (expand-file-name
;;                                  "contrib" (expand-file-name
;;                                             ".." org-dir))))
;;        (load-path (append (list org-dir org-contrib-dir)
;;                           (or load-path nil))))
;;   ;; load up Org-mode and Org-babel
;;   (require 'org-install)
;;   (require 'ob-tangle)
;;   (message "Loaded Org Mode (%.03fs)" (float-time (time-since started-at))))

;; ;; Load up all literate org-mode files in this directory
;; (mapc (lambda (filename)
;;         (let ((started-at (current-time)))
;;           (org-babel-load-file filename)
;;           (message "Loaded Org Babel file: %s (%.03fs)"
;;                    filename (float-time (time-since started-at)))))
;;       (directory-files dotfiles-dir t "\\.org$"))
`

**Comment by servytor** [comment]
Also thank you for your time, I really appreciate it.

**Comment by Artawower** [comment]
No problem, such questions can improve this package and be useful for everybody :)
For point 4 try to replace the keyword :config with :init, because :config will only work for lazy loading
```
(use-package blamer
  :ensure t
  :bind (("s-i" . blamer-show-commit-info))
  :custom
  (blamer-idle-time 0.3)
  (blamer-min-offset 70)
  (blamer-commit-formatter "● %s")
  (blamer-smart-background-p nil)
  :custom-face
  (blamer-face ((t :height 140
                   :italic t)))
  :init
  (global-blamer-mode 1))
  ```

**Comment by servytor** [comment]
Yup, that solves it! Thank you so much!

I will look into the other issues a bit more and if they are not on my end I will actually get some data for you and file a descriptive issue next.
