### ISSUE TITLE
Popup produces line break in terminal

### ISSUE THREAD

**Issue by benjaminor** [Artawower/blamer.el#38]
Hi, related to issues #8 and #28, I experience a line break caused by the blamer popup when running Emacs in terminal (not on every line but on quite a few).

See for example:
![Screenshot from 2023-01-13 10-40-43](https://user-images.githubusercontent.com/29584865/212292517-bd9f5466-2d7f-4426-91ef-cb2969af7e5b.png)

I suspect this is because blamer is using `line-number-display-width` ([documentation](https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#index-line_002dnumber_002ddisplay_002dwidth)) which returns the width used for displaying line numbers but without the padding columns. This leads to a wrong result when calling `blamer--get-line-number-column-width`.
I think you could mitigate this by either adding 2 to the result of `(line-number-display-width)` (for each column left and right of the numbers) or calling `(round (line-number-display-width 'columns))`, at least this fixes the issue in my terminal.

Tested on emacs 28.2 and the current master branch.

**Comment by Artawower** [comment]
Unable to reproduce unfortunately (tested with alacritty and kitty), but `(round (line-number-display-width 'columns))` doesn't seem to break anything. Please check the latest commit

**Comment by benjaminor** [comment]
Yes, fixes the issue. Thanks a lot!

**Comment by Lenbok** [comment]
I'm still getting an off-by-one in the computed window width on the terminal, and am using the following hacky workaround to avoid getting the message truncated on the right with a `$`:
![image](https://github.com/Artawower/blamer.el/assets/282098/03b90e42-fe31-4c3d-86d6-1cb443e5ab16)

Maybe it's the nerd font characters, maybe it's a margin width, who knows?
