### ISSUE TITLE
Default `use-package` setup not working as expected

### ISSUE THREAD

**Issue by chookity-pokk** [Artawower/blamer.el#40]
I am using the default setup given with `use-package` and it enables `global-blamer-mode` on boot, but it doesn't show anything until I disable it and enable it again.

I am using emacs 28.2 on EndeavorOS.

**Comment by Artawower** [comment]
Hey!, Thank you for bug reporting, wouldn't you mind checking that bug exist in the [fix/unexpected-overlay-clearing](https://github.com/Artawower/blamer.el/tree/fix/unexpected-overlay-clearing) branch?

**Comment by chookity-pokk** [comment]
I tried this with the same results. Though I may be testing it incorrectly so here is what I did.

Copied the repo and did a `git checkout` to the suggested branch. Then I added the below snippet to my init file. 

`(add-to-list 'load-path "~/.emacs.d/lisp/blamer.el")`

**Comment by Artawower** [comment]
There is a possibility that it might be downloaded from somewhere else. I merged the fixes from this branch into the master, you can try to update the package through melpa.

If the problem is still exist, please, use fix/windows branch and send log output from *Message* buffer

**Comment by chookity-pokk** [comment]
So I restarted my desktop and it seems to be fixed with the most recent commit. Not exactly sure why it didn't work before the restart but now it does by default. Thank you for the quick responses and the awesome package!
