### ISSUE TITLE
Question about rounded corners

### ISSUE THREAD

**Issue by chookity-pokk** [Artawower/blamer.el#43]
Sorry, this isn't an issue but there isn't a discussions section. 

I was wondering how you managed to get rounded corners for `blamer-show-commit-info`? I tried looking at the code for it but am not super fluent in elisp so I wasn't able to figure it out.

**Comment by Artawower** [comment]
No problem, it's just a box-drawing characters https://en.wikipedia.org/wiki/Box-drawing_character

As I know, there is no way to achieve such a result with native emacs lisp functionality

This is a code for setting such glyphs https://github.com/artawower/blamer.el/blob/master/blamer.el#L152

**Comment by chookity-pokk** [comment]
Sorry for the late response, thanks for the information!
