### ISSUE TITLE
Author name with parens truncated

### ISSUE THREAD

**Issue by jasonmj** [Artawower/blamer.el#45]
I noticed that the author name is not getting formatted correctly when it includes parenthesis, like: `Tom Bombadil (he/him)`. Instead, only `he/him)` gets printed. I suspect this is related to `blamer--regexp-info`.

**Comment by Artawower** [comment]
I think the problem with the regexp, it doesn't catch the first bracket, i'll speculate about it 

![image](https://user-images.githubusercontent.com/16963833/235776004-0ba52abe-6568-4c36-abcd-55d17983a6da.png)

**Comment by Artawower** [comment]
```
(setq blamer--regexp-info
  (concat "^(?\\(?1:[^ ]*\\).*[[:blank:]]\(\\(?2:[^\n]+\\)"
          "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
          "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)"))
```
Can you try to use this regexp ?

**Comment by jasonmj** [comment]
Hmm, that did not seem to help. 

Annoyingly, I did manage to fix it at one point with some testing I did in a scratch buffer, but I lost that work. I'll try to give it another go later... might be next week for me though. Busy times! Thanks for your response and attempt to fix 🙏

**Comment by jasonmj** [comment]
This is working for me: 
```emacs-lisp
(setq blamer--regexp-info
     (concat "^(?\\(?1:[^ ]*\\) [^ ]*[[:blank:]]?\(\\(?2:.*\\)"
	     "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
	     "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)"))
```

**Comment by Artawower** [comment]
Unfortunately, It doesn't work with the author's name without spaces, for example

`(^3130q6ze (TomBombadil(he/him) 2020-12-16 16:28:09 +0800 4) $tooltip-border-radius: 2px;)`

Could you try this one?
```
(concat "(\\(?1:[^ ]*\\) (\\(?2:.*\\)"
	        "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
	        "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)")
```

**Comment by jasonmj** [comment]
Hmm, your blame message looks different than what I typically have. Here's what I've been testing with: 

```emacs-lisp
(setq blamer--regexp-info
  (concat "^(?\\(?1:[^ ]*\\) [^ ]*[[:blank:]]?\(\\(?2:.*\\)"
          "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
          "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)"))

(setq-local blame-msg "3b90f8b82 lib/project_web/live/installation_live/show.html.heex (TomBombadil(he/him) 2023-03-16 08:08:26 -0500 25)     <div class=\"flex justify-between gap-4\">")

(string-match blamer--regexp-info blame-msg)
(message "%s" (match-string 2 blame-msg))
```

The latest regex you posted did not work with my blame-msg.

**Comment by Artawower** [comment]
sorry for the inconvenience, I try to find a silver bullet for this problem. Can you check this regexp please?
```
(concat "(\\(?1:[^ ]*\\) \\([^ ]* \\)?(\\(?2:.*\\)"
	        "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
	        "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)")
```

![image](https://github.com/Artawower/blamer.el/assets/16963833/148895cb-1963-47b8-9c8f-477d66ae791e)

**Comment by Artawower** [comment]
Oh, i got it, my tests were wrong. Sorry for the inconvenience, I try to find a silver bullet for this problem. Can you check this regexp please?
```
(concat "^\\(?1:[^ ]*\\) \\(?5:[^ ]* \\)?(\\(?2:.*\\)"
	        "\s\\(?3:[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\)"
	        "\s\\(?4:[0-9]\\{2\\}:[0-9]\\{2\\}:[0-9]\\{2\\}\\)")
```
before
![image](https://github.com/Artawower/blamer.el/assets/16963833/c68be19f-5ba5-4204-8577-5ab193fc0a66)
after

![image](https://github.com/Artawower/blamer.el/assets/16963833/501999cb-a31a-42b1-9e32-fa02978aa5eb)

**Comment by jasonmj** [comment]
It's working for me :tada: 

Thanks for your help here. It's been nice working with you.
