### ISSUE TITLE
Potential optimization?

### ISSUE THREAD

**Issue by Shooooooooo** [Artawower/blamer.el#50]
The repository I am working on daily basis has many commits. The git blame operation itself takes several seconds. It is making operation in Emacs very slow once I enable Blamer. Do you think there is an opportunity for optimization by caching the git blame result? Thanks!

**Comment by Artawower** [comment]
Hi! I don't think caching would be a good idea in this case, it's not easy to sync the cache, plus when working with editable text the cache will have to be cleared after each change.

I've described one optimization option that won't block emacs https://www.reddit.com/r/emacs/comments/11gczbj/comment/jaxdrcl/?utm_source=share&utm_medium=web2x&context=3.


I will try to revise this implementation as soon as I have some more free time. It won't speed up blamer itself, but it will eliminate the emacs slowdown.

**Comment by Artawower** [comment]
Could you try this branch? `enhancement/async-cmd` Is it still as slow or has something changed?

**Comment by Shooooooooo** [comment]
Sorry for the slow reply. It may be a bit faster compared to master branch but still slow. If the intention is to make the git operation async, my control still freezes when it's loading the blame info.

**Comment by Shooooooooo** [comment]
Actually, I was wrong. Now that I’ve cleaned up my straight area and rebuild blamer.el. My control no longer freezes when loading commit info! Yay! Now I am finally able to enable blamer.el by default. Thank you so much!

**Comment by Artawower** [comment]
This feature has recently been merged 🫡.  If you have any questions about it, please create a new issue
