### ISSUE TITLE
Clickable Annotations

### ISSUE THREAD

**Issue by alhassy** [Artawower/blamer.el#7]
Thank-you for making this nice package 😁 

It would be nice if we could click on a git blame annotation to get the associated commit in another buffer ---LSP allows clickable annotations. Alternatively, instead of a click, perhaps a key combination to show the full log for that commit would be helpful.

A workaround I'm using is as follows:
1. When you see a git blame annotations, then...
2. Press `C-u M-x magit-show-commit` and, if you have Helm or another compleition mechanism then you'll see the commit hash for that line...
3. So just press `Return`.

**Comment by Artawower** [comment]
I've changed access to annotation binding a bit. Now to implement the functionality you need you can pass alist from pairs `<mapvar> . callback` function, with commit-info argument (plist)

<details>
<summary>commit info detail</summary>

:commit-hash - hash of clicked commit
:commit-author - author name after formatting
:raw-commit-author - raw author username if exist.
:commit-date - date of commit. (string field)
:commit-time - commit's time. (string field)
:commit-message - message of commit. If not exist will be get from
`blamer-uncommitted-changes-message' variable.
</details>

For example, if you want to bind left click for opening magit commit diff and right click for browse info in the browser, you can use this code:

```elisp
  (defun blamer-callback-show-commit-diff (commit-info)
    (interactive)
    (let ((commit-hash (plist-get commit-info :commit-hash)))
      (when commit-hash
        (magit-show-commit commit-hash))))

  (defun blamer-callback-open-remote (commit-info)
    (interactive)
    (let ((commit-hash (plist-get commit-info :commit-hash)))
      (when commit-hash
        (message commit-hash)
        (forge-browse-commit commit-hash))))

  (setq blamer-bindings '(("<mouse-3>" . blamer-callback-open-remote)
                          ("<mouse-1>" . blamer-callback-show-commit-diff)))

```
