### ISSUE TITLE
Default `blamer--commit-message-regexp` on Windows systerm don't display commit.

### ISSUE THREAD

**Issue by ISouthRain** [Artawower/blamer.el#72]
Hello, everybody!
```emacs-lisp
;; This my configuration
(setq blamer--commit-message-regexp "\n[\s]+\\(\\(?:.\\|\n\\)+\\):?")
;; Is display OK!
```
![图片](https://github.com/user-attachments/assets/c121f528-9639-4c6a-94f4-d51f82a78f57)

```emacs-lisp
;; This blamer default
(setq blamer--commit-message-regexp "\n\n[\s]+\\(\\(?:.\\|\n\\)+\\):?")
;; Don't Dispaly
```
![图片](https://github.com/user-attachments/assets/4d7ac793-11c5-4bc7-a6f6-d6f186be6935)

This is BUG ????
It seems like different git platforms lead to different results?
I only understand so much so far, how else should I determine the problem?

**Comment by Artawower** [comment]
Hey! Thanks for such a good investigation. Are you sure the problem is with the Windows system? It looks like your commit message doesn’t have an additional newline symbol.

If it’s not a private commit message, would you mind providing me with the output from the following code from the \*Messages\* buffer? Otherwise, I need a similar commit message with any text that can reproduce the problem.

```emacs-lisp
(blamer--get-async-blame-info
 (buffer-file-name)
 (current-line)
 (current-line)
 (lambda (res)
   (string-match blamer--regexp-info res)
   (let ((commit-hash (string-trim (match-string 1 res))))
     (message "\"%s\"" commit-hash)
     (blamer--async-get-email-commit-message
      commit-hash
      (lambda (commit-message)
        (message "Commit message:")
        (message "\"%s\"" commit-message)
        (message "-------------------------------"))))))
```

This code should be evaluated when the cursor is under the problematic line

**Comment by ISouthRain** [comment]
> Hey! Thanks for such a good investigation. Are you sure the problem is with the Windows system? It looks like your commit message doesn’t have an additional newline symbol.
> 
> If it’s not a private commit message, would you mind providing me with the output from the following code from the *Messages* buffer? Otherwise, I need a similar commit message with any text that can reproduce the problem.
> 
> ```emacs-lisp
> (blamer--get-async-blame-info
>  (buffer-file-name)
>  (current-line)
>  (current-line)
>  (lambda (res)
>    (string-match blamer--regexp-info res)
>    (let ((commit-hash (string-trim (match-string 1 res))))
>      (message "\"%s\"" commit-hash)
>      (blamer--async-get-email-commit-message
>       commit-hash
>       (lambda (commit-message)
>         (message "Commit message:")
>         (message "\"%s\"" commit-message)
>         (message "-------------------------------"))))))
> ```
> 
> This code should be evaluated when the cursor is under the problematic line

Test:
```emacs-lisp
;; This use blamer default `blamer--commit-message-regexp` test.
;; Message out:
"b645fb97"
Commit message:
"(isouthrain@gmail.com commit b645fb973309696f51719b03f8a4f478a0e670f2

Author: ISouthRain <my@gmail.com>

Date:   Sun Aug 4 12:35:21 2024 +0800



    deadgrep: Add this package: 替代 rg(ripgrep) 包

)"
-------------------------------

;; This ok.
```

**Comment by Artawower** [comment]
That’s a bit weird. When I check both of the provided regex patterns in the regex builder, I see the correct group results

<img width="738" alt="image" src="https://github.com/user-attachments/assets/965c4179-8da0-49f9-ac6b-cebc2fca1125">

<img width="689" alt="image" src="https://github.com/user-attachments/assets/7b971407-d32a-4966-b12d-6978d8efd246">

Could you check it in the regexp builder?

Also, how will it work with a more precise regex: "Date:.*\n\n+[[:blank:]]+\\(\\(.\\|\n\\)+\\):?"

**Comment by ISouthRain** [comment]
![图片](https://github.com/user-attachments/assets/7682f409-13a3-48e2-926b-a4a068fc8319)
I think the reason may be that my output here is only one line?

**Comment by Artawower** [comment]
Hmm, got it. I think a regular expression should still take into account the specifics of windows out of the box, unfortunately I can't debug this regular expression because I don't have a windows system at hand. Could you try this regular expression? 

`"\r?\n\r?\n[\s]+\\(\\(?:.\\|\r?\n\\)+\\):?"`

It supposedly adds an optional \r before each \n, which doesn't affect linux systems, but also adds support for windows users.

**Comment by ISouthRain** [comment]
> Hmm, got it. I think a regular expression should still take into account the specifics of windows out of the box, unfortunately I can't debug this regular expression because I don't have a windows system at hand. Could you try this regular expression?
> 
> `"\r?\n\r?\n[\s]+\\(\\(?:.\\|\r?\n\\)+\\):?"`
> 
> It supposedly adds an optional \r before each \n, which doesn't affect linux systems, but also adds support for windows users.

Ohh, Thanks you!
==> `"\r?\n\r?\n[\s]+\\(\\(?:.\\|\r?\n\\)+\\):?"`
Working normally.

**Comment by ISouthRain** [comment]
Now let's discuss another issue...
Because I found a new problem, I'm sorry.
This question is not related to the issue discussed above.
Q: Does blamer not support commit processing of all CJK characters?
![动画1](https://github.com/user-attachments/assets/5f7e86a7-218f-4d2d-92b2-67a0e2aacc4a)
![20240908_091114](https://github.com/user-attachments/assets/4d71cebe-815a-4d76-9a3a-3ce4166b1255)
![20240908_091425](https://github.com/user-attachments/assets/b11049d8-dd27-428e-a9a0-6dc4a068a814)

Should I discuss new issues here or should I open new issues?

**Comment by Artawower** [comment]
We can continue here. I don't think the problem is CJK characters. In Line 1885 there is no message output itself, I am a bit confused that in the console the commit starts with “fcb...” and in *Messages* with “^fcb”.

Let's make some investigation. Firstly, let's try to get raw output from the `blamer--get-async-blame-info`:

```emacs-lisp
(blamer--get-async-blame-info
 (buffer-file-name)
 (current-line)
 (current-line)
 (lambda (res)
   (message "async blame info: \"%s\"" res)
   (string-match blamer--regexp-info res)
   (let ((commit-hash (string-trim (match-string 1 res))))
     (message "\"%s\"" commit-hash)
     (blamer--async-get-email-commit-message
      commit-hash
      (lambda (commit-message)
        (message "Commit message:")
        (message "\"%s\"" commit-message)
        (message "-------------------------------"))))))
```

(I added additional log for checking raw output)

Also, what happens if you type `git log -n1 <commit-hash-from-messages-buffer>`? (for example ^fcb7278)

Please provide text, not screenshots 🙏🏻, it is more convenient to work with text and copy logs from it.

**Comment by ISouthRain** [comment]
```shell
----------------------------------
Current-Line is: 1885
async blame info: "^fcb7278 (ISouthRain 2024-03-30 15:30:24 +0800 1885)   (magit-diff-refine-hunk t)

"
"^fcb7278"
Commit message:
"( )"
-------------------------------
----------------------------------
Current-Line is: 1886
async blame info: "50dc1389 (ISouthRain 2024-08-04 12:41:51 +0800 1886)   (magit-ediff-dwim-show-on-hunks t)

"
"50dc1389"
Commit message:
"(isouthrain@gmail.com commit 50dc1389ee80c388966b05bfd9a8dce3c823e86d

Author: ISouthRain <isouthrain@gmail.com>

Date:   Sun Aug 4 12:41:51 2024 +0800



    magit: 添加自动分裂窗口功能

)"
-------------------------------
```

Terminal: 
```shell
PS C:\Users\Jack\AppData\Roaming\.freedom.d> git log -n1 fcb727834c5e2db520155420c54b416c821cc328
commit fcb727834c5e2db520155420c54b416c821cc328
Author: ISouthRain <isouthrain@gmail.com>
Date:   Sat Mar 30 15:30:24 2024 +0800

    初始化
PS C:\Users\Jack\AppData\Roaming\.freedom.d> git log -n1 50dc1389ee80c388966b05bfd9a8dce3c823e86d
commit 50dc1389ee80c388966b05bfd9a8dce3c823e86d
Author: ISouthRain <isouthrain@gmail.com>
Date:   Sun Aug 4 12:41:51 2024 +0800

    magit: 添加自动分裂窗口功能
```

**Comment by ISouthRain** [comment]
> @Artawower
> 
> ```shell
> ----------------------------------
> Current-Line is: 1885
> async blame info: "^fcb7278 (ISouthRain 2024-03-30 15:30:24 +0800 1885)   (magit-diff-refine-hunk t)
> 
> "
> "^fcb7278"
> Commit message:
> "( )"
> -------------------------------
> ----------------------------------
> Current-Line is: 1886
> async blame info: "50dc1389 (ISouthRain 2024-08-04 12:41:51 +0800 1886)   (magit-ediff-dwim-show-on-hunks t)
> 
> "
> "50dc1389"
> Commit message:
> "(isouthrain@gmail.com commit 50dc1389ee80c388966b05bfd9a8dce3c823e86d
> 
> Author: ISouthRain <isouthrain@gmail.com>
> 
> Date:   Sun Aug 4 12:41:51 2024 +0800
> 
> 
> 
>     magit: 添加自动分裂窗口功能
> 
> )"
> -------------------------------
> ```
> 
> Terminal:
> 
> ```shell
> PS C:\Users\Jack\AppData\Roaming\.freedom.d> git log -n1 fcb727834c5e2db520155420c54b416c821cc328
> commit fcb727834c5e2db520155420c54b416c821cc328
> Author: ISouthRain <isouthrain@gmail.com>
> Date:   Sat Mar 30 15:30:24 2024 +0800
> 
>     初始化
> PS C:\Users\Jack\AppData\Roaming\.freedom.d> git log -n1 50dc1389ee80c388966b05bfd9a8dce3c823e86d
> commit 50dc1389ee80c388966b05bfd9a8dce3c823e86d
> Author: ISouthRain <isouthrain@gmail.com>
> Date:   Sun Aug 4 12:41:51 2024 +0800
> 
>     magit: 添加自动分裂窗口功能
> ```

In other git projects, I try to use:
初始化
As a commit, blamer output is normal.

**Comment by Artawower** [comment]
> git log -n1 fcb727834c5e2db520155420c54b416c821cc328

What if you try `git log -n1 ^fcb7278`? Because blamer uses a short SHA to get a detailed commit message

> In other git projects, I try to use:
初始化
As a commit, blamer output is normal.

Yep, it looks like the real reason is accessing the incorrect commit by its hash. I blame the ^ symbol, but we need to make sure of it

**Comment by ISouthRain** [comment]
> > git log -n1 fcb727834c5e2db520155420c54b416c821cc328
> 
> What if you try `git log -n1 ^fcb7278`? Because blamer uses a short SHA to get a detailed commit message
> 
> > In other git projects, I try to use:
> > 初始化
> > As a commit, blamer output is normal.
> 
> Yep, it looks like the real reason is accessing the incorrect commit by its hash. I blame the ^ symbol, but we need to make sure of it

```shell
git log -n1 ^fcb7278
# Not output.
```

My head is `fcb727834c5e2db520155420c54b416c821cc328` Why does it become ^fcb7278 when using `blamer`??

**Comment by Artawower** [comment]
Yeah it looks weird, can't figure out yet who exactly adds the ^ and under what circumstances....

I apologize for trying to introduce something in eval so often, but I don't see how I can debug it otherwise yet.

Could you please enter:

`(apply #'vc-git--run-command-string “<full-file-path>” '(“blame” “-L” “1885,1885”)))`

And if it will return the ^ symbol, could you check the same command from cli?

`git blame -L 1885,1885 <file-path>`.

**Comment by ISouthRain** [comment]
#+begin_src emacs-lisp :tangle no
(apply #'vc-git--run-command-string "~/.freedom.d/config.org" '("blame" "-L" "1884,1884"))
#+end_src

#+RESULTS:
: ^fcb7278 (ISouthRain 2024-03-30 15:30:24 +0800 1884)   (magit-diff-refine-hunk t)


git blame -L 1884,1884 config.org
^fcb7278 (ISouthRain 2024-03-30 15:30:24 +0800 1884)   (magit-diff-refine-hunk t)

**Comment by Artawower** [comment]
I think I've figured out where the symbol comes from.  Try version 0.9.4

**Comment by ISouthRain** [comment]
Thanks you!
no problem.
