### ISSUE TITLE
Right Alignment Display Problems

### ISSUE THREAD

**Issue by brownts** [Artawower/blamer.el#8]
The current calculation (in `blamer--format-commit-info`) to determine the offset when right alignment is configured, doesn't work correctly when `display-line-numbers-mode` is active.  This can be easily observed by enabling `display-line-numbers-mode` and configuring blamer.el to use right alignment (i.e., `(setq blamer-view 'overlay-right)`).  This will cause the overlay to either wrap or be truncated unnecessarily, depending on the `truncate-lines` setting.

The reason this doesn't work correctly is due to the fact that the space in the window taken up by the line number itself is not included in the value returned from `window-width`.  The space consumed by the line number must be explicitly accounted for via the use of the `line-number-display-width` function.  This is discussed [here](https://lists.gnu.org/archive/html/bug-gnu-emacs/2017-08/msg01054.html).

Here is an example for [LSP UI #1](https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-util.el#L47) and [LSP UI #2](https://github.com/emacs-lsp/lsp-ui/pull/546#issuecomment-753466253) and [Company Mode](https://github.com/company-mode/company-mode/blob/master/company.el#L1026).  It appears 2 must be added to the result of `line-number-display-width`.  I'm not entirely certain why that is the case as I haven't found any documentation as to why that is needed, but the links to the examples provided all use that.  I know from experimentation that using the value provided by `line-number-display-width` is not sufficient however, and does require 2 to be added to this value.

The second issue I noticed is the fact that as part of this offset calculation, the length of the line is being calculated after it is trimmed  (`(string-trim-right (thing-at-point 'line))`).  The problem is that if any space is trimmed this will affect the overlay and push it further to the right.  This is immediately obvious on lines containing trailing spaces, and can be easily seen by adding a space (or more) to the end of a line and watching the overlay shift to the right unnecessarily causing wrapping or truncating.

**Comment by Artawower** [comment]
Should be fixed in the last commit

**Comment by brownts** [comment]
Yes, this is now fixed.  Thank you!
